name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lints:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  no_std:
    name: no_std
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain for ARM
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7a-none-eabi

      - name: Set up cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build binary for armv7a-none-eabi
        run: cargo rustc --target=armv7a-none-eabi --manifest-path=ensure_no_std/Cargo.toml

  tests:
    name: tests (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - "1.89.0"
          - stable
          - beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Set up cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run cargo test (default features)
        run: cargo test --no-fail-fast --workspace -- --nocapture

      - name: Run cargo test (all features)
        run: cargo test --all-features --no-fail-fast --workspace -- --nocapture